### ISSUE TITLE
ejabberd current version

### ISSUE THREAD

**Issue by Neustradamus** [fabiang/sasl#10]
Maybe good to update the code?

Official ejabberd docker:
- https://github.com/processone/docker-ejabberd

**Comment by fabiang** [comment]
Do we have any advantage of updating to a newer version? I mean Ejabberd is only used to run the integration tests against it.

**Comment by Neustradamus** [comment]
@fabiang: Better to use the official docker, the right place ^^
And in more, ejabberd has been updated since the unofficial place.

**Comment by fabiang** [comment]
Changing to the official image only means unnecessary work for no advantage. I'm sorry but I close this as wont-fix.

**Comment by fabiang** [comment]
I've needed to upgrade Ejabberd to 23.10 to test the other auth mechanisms, therefore this has been fixed.
