### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by edhelas** [fabiang/sasl#5]
It seems that the lib is failing with PHP7.4 

    PHP Warning:  file_get_contents(): stream does not support seeking in /var/www/html/movim/vendor/fabiang/sasl/src/Authentication/AbstractAuthentication.php on line 92
    PHP Warning:  file_get_contents(): Failed to seek to position -1 in the stream in /var/www/html/movim/vendor/fabiang/sasl/src/Authentication/AbstractAuthentication.php on line 92

I was able to fix the issue by replacing

    return base64_encode(file_get_contents($file, false, null, -1, 32));

with 

    return base64_encode(file_get_contents($file, false, null, 0, 32));

In the file.
I'd be pleased if you can release this fix :)

**Comment by fabiang** [comment]
Seems to me I've used the wrong default parameter for the `$seek` parameter there. Fixed in master an tagged a v1.0.1.

**Comment by edhelas** [comment]
Thanks a lot !

**Comment by Neustradamus** [comment]
@edhelas: Have you planned to update your repository? :)

@edhelas, @fabiang: There are two PRs:
- https://github.com/fabiang/sasl/pull/3
- https://github.com/edhelas/sasl2/pull/2

Can you look for SCRAM?
- https://github.com/edhelas/sasl2/issues/3
- https://github.com/fabiang/sasl/issues/4
